import type { AgentInventoryItem } from '@bedrex/shared';

const MOCK_ACCOUNT_ID = '000000000000';

const allMockAgents: AgentInventoryItem[] = [
  // === Playlist Agents (matching real ones) ===
  {
    id: 'mock-playlist-agent-1',
    name: 'playlistAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    description: 'Creates and manages music playlists based on user preferences and mood',
    instruction: 'You are a music playlist assistant. Help users create, manage, and discover playlists based on their preferences, mood, and listening history.',
    agentVersion: '2',
    createdAt: '2025-04-17T13:59:28.081Z',
    updatedAt: '2025-06-10T09:15:00.000Z',
    actionGroups: [
      {
        id: 'ag-create-playlist',
        name: 'CreatePlaylist',
        description: 'Creates a new playlist with specified tracks',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:create-playlist`,
        state: 'ENABLED',
        updatedAt: '2025-04-17T14:00:00.000Z',
      },
      {
        id: 'ag-search-tracks',
        name: 'SearchTracks',
        description: 'Searches for tracks by artist, genre, or mood',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:search-tracks`,
        state: 'ENABLED',
        updatedAt: '2025-04-17T14:00:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-music-catalog',
        name: 'Music Catalog',
        description: 'Music catalog with artist and genre data',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-04-17T14:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 342,
      avgLatencyMs: 1250,
      errorRate: 0.02,
      totalTokensUsed24h: 85000,
      estimatedCost24h: 0.43,
    },
  },
  {
    id: 'mock-playlist-agent-2',
    name: 'playlistAgentv2',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    description: 'Enhanced playlist agent v2 with collaborative filtering and social features',
    instruction: 'You are an advanced music playlist assistant v2. You can collaborate with users, suggest tracks based on social listening data, and create shared playlists.',
    agentVersion: '3',
    createdAt: '2025-05-01T10:00:00.000Z',
    updatedAt: '2025-07-15T11:30:00.000Z',
    actionGroups: [
      {
        id: 'ag-collab-playlist',
        name: 'CollaborativePlaylist',
        description: 'Creates collaborative playlists with multiple contributors',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:collab-playlist`,
        state: 'ENABLED',
        updatedAt: '2025-05-01T10:30:00.000Z',
      },
      {
        id: 'ag-social-recommend',
        name: 'SocialRecommendations',
        description: 'Recommends tracks based on friends listening activity',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:social-recommend`,
        state: 'ENABLED',
        updatedAt: '2025-05-01T10:30:00.000Z',
      },
      {
        id: 'ag-search-tracks-v2',
        name: 'SearchTracksV2',
        description: 'Enhanced track search with semantic understanding',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:search-tracks-v2`,
        state: 'ENABLED',
        updatedAt: '2025-05-01T10:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-music-catalog-v2',
        name: 'Music Catalog V2',
        description: 'Enhanced music catalog with listening patterns and social data',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-05-01T11:00:00.000Z',
      },
      {
        knowledgeBaseId: 'kb-user-preferences',
        name: 'User Preferences',
        description: 'User preference profiles and listening history',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-05-01T11:00:00.000Z',
      },
    ],
    guardrail: {
      guardrailId: 'gr-content-filter-1',
      guardrailVersion: '1',
      name: 'Content Safety Filter',
    },
    metrics: {
      invocationCount24h: 587,
      avgLatencyMs: 980,
      errorRate: 0.01,
      totalTokensUsed24h: 145000,
      estimatedCost24h: 0.72,
    },
  },
  {
    id: 'mock-playlist-creator',
    name: 'playlistCreator',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-haiku-20240307-v1:0',
    description: 'Lightweight playlist creator for quick playlist generation',
    instruction: 'You are a fast playlist creator. Generate playlists quickly based on simple prompts like genre, mood, or activity.',
    agentVersion: '1',
    createdAt: '2025-06-01T08:00:00.000Z',
    updatedAt: '2025-06-01T08:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-quick-create',
        name: 'QuickCreate',
        description: 'Rapidly generates a playlist from a single prompt',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:quick-create`,
        state: 'ENABLED',
        updatedAt: '2025-06-01T08:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 1205,
      avgLatencyMs: 420,
      errorRate: 0.005,
      totalTokensUsed24h: 62000,
      estimatedCost24h: 0.02,
    },
  },

  // === Customer Service Agents ===
  {
    id: 'mock-cs-agent-1',
    name: 'customerSupportAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    description: 'Handles customer support inquiries including order status, returns, and account issues',
    instruction: 'You are a customer support agent. Help customers with their inquiries about orders, returns, account issues, and product information. Always be polite and professional.',
    agentVersion: '5',
    createdAt: '2025-02-15T09:00:00.000Z',
    updatedAt: '2025-08-01T14:20:00.000Z',
    actionGroups: [
      {
        id: 'ag-order-lookup',
        name: 'OrderLookup',
        description: 'Looks up order status and details',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:order-lookup`,
        state: 'ENABLED',
        updatedAt: '2025-02-15T09:30:00.000Z',
      },
      {
        id: 'ag-initiate-return',
        name: 'InitiateReturn',
        description: 'Starts the return process for an order',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:initiate-return`,
        state: 'ENABLED',
        updatedAt: '2025-02-15T09:30:00.000Z',
      },
      {
        id: 'ag-escalate-ticket',
        name: 'EscalateTicket',
        description: 'Escalates a support ticket to a human agent',
        executionType: 'RETURN_CONTROL',
        state: 'ENABLED',
        updatedAt: '2025-02-15T09:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-product-catalog',
        name: 'Product Catalog',
        description: 'Complete product catalog with specifications and FAQs',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-02-15T10:00:00.000Z',
      },
      {
        knowledgeBaseId: 'kb-return-policy',
        name: 'Return Policy',
        description: 'Return and refund policy documents',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-02-15T10:00:00.000Z',
      },
    ],
    guardrail: {
      guardrailId: 'gr-cs-safety-1',
      guardrailVersion: '2',
      name: 'Customer Service Safety',
    },
    metrics: {
      invocationCount24h: 2847,
      avgLatencyMs: 1100,
      errorRate: 0.008,
      totalTokensUsed24h: 520000,
      estimatedCost24h: 2.60,
    },
  },
  {
    id: 'mock-cs-agent-2',
    name: 'billingAssistant',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-sonnet-20240229-v1:0',
    description: 'Assists customers with billing inquiries, payment issues, and invoice generation',
    instruction: 'You are a billing assistant. Help customers understand their invoices, resolve payment issues, and manage subscription billing.',
    agentVersion: '2',
    createdAt: '2025-03-10T11:00:00.000Z',
    updatedAt: '2025-07-20T08:45:00.000Z',
    actionGroups: [
      {
        id: 'ag-billing-lookup',
        name: 'BillingLookup',
        description: 'Retrieves billing history and invoice details',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:billing-lookup`,
        state: 'ENABLED',
        updatedAt: '2025-03-10T11:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-billing-faq',
        name: 'Billing FAQ',
        description: 'Frequently asked questions about billing and payments',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-03-10T12:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 956,
      avgLatencyMs: 890,
      errorRate: 0.015,
      totalTokensUsed24h: 198000,
      estimatedCost24h: 0.99,
    },
  },
  {
    id: 'mock-cs-agent-3',
    name: 'techSupportBot',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-west-2',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-haiku-20241022-v1:0',
    description: 'Provides technical support for software products and troubleshooting guidance',
    instruction: 'You are a technical support bot. Help users troubleshoot software issues, provide step-by-step solutions, and escalate complex problems.',
    agentVersion: '4',
    createdAt: '2025-01-20T15:00:00.000Z',
    updatedAt: '2025-08-05T16:30:00.000Z',
    actionGroups: [
      {
        id: 'ag-diagnostics',
        name: 'RunDiagnostics',
        description: 'Runs automated diagnostic checks',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-west-2:${MOCK_ACCOUNT_ID}:function:run-diagnostics`,
        state: 'ENABLED',
        updatedAt: '2025-01-20T15:30:00.000Z',
      },
      {
        id: 'ag-create-ticket',
        name: 'CreateSupportTicket',
        description: 'Creates a support ticket in the ticketing system',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-west-2:${MOCK_ACCOUNT_ID}:function:create-ticket`,
        state: 'ENABLED',
        updatedAt: '2025-01-20T15:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-tech-docs',
        name: 'Technical Documentation',
        description: 'Product documentation, troubleshooting guides, and known issues',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-01-20T16:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 1543,
      avgLatencyMs: 650,
      errorRate: 0.012,
      totalTokensUsed24h: 310000,
      estimatedCost24h: 0.37,
    },
  },
  {
    id: 'mock-cs-agent-4',
    name: 'onboardingAssistant',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.nova-pro-v1:0',
    description: 'Guides new customers through product onboarding and setup processes',
    instruction: 'You are an onboarding assistant. Guide new users through account setup, product configuration, and initial tutorials.',
    agentVersion: '1',
    createdAt: '2025-07-01T10:00:00.000Z',
    updatedAt: '2025-07-01T10:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-setup-account',
        name: 'SetupAccount',
        description: 'Helps configure user account settings',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:setup-account`,
        state: 'ENABLED',
        updatedAt: '2025-07-01T10:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-onboarding-guides',
        name: 'Onboarding Guides',
        description: 'Step-by-step onboarding and setup guides',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-07-01T11:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 423,
      avgLatencyMs: 780,
      errorRate: 0.003,
      totalTokensUsed24h: 95000,
      estimatedCost24h: 0.38,
    },
  },

  // === Data Analysis Agents ===
  {
    id: 'mock-data-agent-1',
    name: 'salesAnalyticsAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-opus-20240229-v1:0',
    description: 'Analyzes sales data, generates reports, and provides business intelligence insights',
    instruction: 'You are a sales analytics agent. Analyze sales data, identify trends, generate reports, and provide actionable business insights.',
    agentVersion: '3',
    createdAt: '2025-03-01T09:00:00.000Z',
    updatedAt: '2025-07-28T12:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-query-sales-db',
        name: 'QuerySalesDatabase',
        description: 'Executes queries against the sales data warehouse',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:query-sales-db`,
        state: 'ENABLED',
        updatedAt: '2025-03-01T09:30:00.000Z',
      },
      {
        id: 'ag-generate-report',
        name: 'GenerateReport',
        description: 'Generates formatted sales reports',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:generate-report`,
        state: 'ENABLED',
        updatedAt: '2025-03-01T09:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-sales-metrics',
        name: 'Sales Metrics Dictionary',
        description: 'Definitions of sales KPIs, metrics, and business terminology',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-03-01T10:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 156,
      avgLatencyMs: 3200,
      errorRate: 0.04,
      totalTokensUsed24h: 280000,
      estimatedCost24h: 6.30,
    },
  },
  {
    id: 'mock-data-agent-2',
    name: 'logAnalyzer',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-west-2',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-haiku-20241022-v1:0',
    description: 'Analyzes application logs to detect anomalies, errors, and performance issues',
    instruction: 'You are a log analysis agent. Parse and analyze application logs to identify errors, anomalies, and performance bottlenecks.',
    agentVersion: '2',
    createdAt: '2025-04-10T14:00:00.000Z',
    updatedAt: '2025-06-20T09:15:00.000Z',
    actionGroups: [
      {
        id: 'ag-query-logs',
        name: 'QueryLogs',
        description: 'Queries CloudWatch Logs and OpenSearch for log entries',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-west-2:${MOCK_ACCOUNT_ID}:function:query-logs`,
        state: 'ENABLED',
        updatedAt: '2025-04-10T14:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 89,
      avgLatencyMs: 1800,
      errorRate: 0.03,
      totalTokensUsed24h: 120000,
      estimatedCost24h: 0.14,
    },
  },
  {
    id: 'mock-data-agent-3',
    name: 'financialReportAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'eu-west-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-sonnet-20240229-v1:0',
    description: 'Generates financial reports and performs budget analysis for the European market',
    instruction: 'You are a financial reporting agent. Generate financial summaries, analyze budgets, and create compliance reports for EU operations.',
    agentVersion: '2',
    createdAt: '2025-05-15T08:00:00.000Z',
    updatedAt: '2025-08-01T07:30:00.000Z',
    actionGroups: [
      {
        id: 'ag-finance-query',
        name: 'FinanceQuery',
        description: 'Queries the financial data lake',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:eu-west-1:${MOCK_ACCOUNT_ID}:function:finance-query`,
        state: 'ENABLED',
        updatedAt: '2025-05-15T08:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-eu-regulations',
        name: 'EU Financial Regulations',
        description: 'EU financial compliance regulations and reporting standards',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-05-15T09:00:00.000Z',
      },
    ],
    guardrail: {
      guardrailId: 'gr-finance-pii-1',
      guardrailVersion: '1',
      name: 'Financial PII Protection',
    },
    metrics: {
      invocationCount24h: 67,
      avgLatencyMs: 2100,
      errorRate: 0.01,
      totalTokensUsed24h: 95000,
      estimatedCost24h: 0.48,
    },
  },

  // === Code Review / Development Agents ===
  {
    id: 'mock-code-agent-1',
    name: 'codeReviewAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    description: 'Reviews pull requests, identifies bugs, and suggests code improvements',
    instruction: 'You are a code review agent. Analyze code changes, identify potential bugs, suggest improvements, and ensure coding standards compliance.',
    agentVersion: '4',
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-07-30T15:45:00.000Z',
    actionGroups: [
      {
        id: 'ag-fetch-pr',
        name: 'FetchPullRequest',
        description: 'Fetches pull request details and diff from GitHub',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:fetch-pr`,
        state: 'ENABLED',
        updatedAt: '2025-01-10T10:30:00.000Z',
      },
      {
        id: 'ag-post-review',
        name: 'PostReviewComment',
        description: 'Posts review comments on a pull request',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:post-review`,
        state: 'ENABLED',
        updatedAt: '2025-01-10T10:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-coding-standards',
        name: 'Coding Standards',
        description: 'Company coding standards, style guides, and best practices',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-01-10T11:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 234,
      avgLatencyMs: 2800,
      errorRate: 0.025,
      totalTokensUsed24h: 450000,
      estimatedCost24h: 2.25,
    },
  },
  {
    id: 'mock-code-agent-2',
    name: 'testGeneratorAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-sonnet-20240229-v1:0',
    description: 'Automatically generates unit tests and integration tests for codebases',
    instruction: 'You are a test generation agent. Analyze source code and generate comprehensive unit tests and integration tests with good coverage.',
    agentVersion: '2',
    createdAt: '2025-04-20T11:00:00.000Z',
    updatedAt: '2025-06-15T13:20:00.000Z',
    actionGroups: [
      {
        id: 'ag-analyze-code',
        name: 'AnalyzeSourceCode',
        description: 'Reads and analyzes source code files',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:analyze-code`,
        state: 'ENABLED',
        updatedAt: '2025-04-20T11:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-testing-patterns',
        name: 'Testing Patterns',
        description: 'Testing patterns, frameworks documentation, and examples',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-04-20T12:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 178,
      avgLatencyMs: 2200,
      errorRate: 0.018,
      totalTokensUsed24h: 320000,
      estimatedCost24h: 1.60,
    },
  },
  {
    id: 'mock-code-agent-3',
    name: 'infraAsCodeAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-west-2',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.nova-pro-v1:0',
    description: 'Generates and reviews infrastructure as code (CDK, Terraform, CloudFormation)',
    instruction: 'You are an IaC agent. Generate, review, and optimize infrastructure as code templates. Support CDK, Terraform, and CloudFormation.',
    agentVersion: '1',
    createdAt: '2025-06-10T09:00:00.000Z',
    updatedAt: '2025-06-10T09:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-validate-template',
        name: 'ValidateTemplate',
        description: 'Validates IaC templates against best practices',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-west-2:${MOCK_ACCOUNT_ID}:function:validate-template`,
        state: 'ENABLED',
        updatedAt: '2025-06-10T09:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-aws-best-practices',
        name: 'AWS Best Practices',
        description: 'AWS Well-Architected Framework and IaC best practices',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-06-10T10:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 45,
      avgLatencyMs: 1500,
      errorRate: 0.02,
      totalTokensUsed24h: 68000,
      estimatedCost24h: 0.27,
    },
  },

  // === Content Generation Agents ===
  {
    id: 'mock-content-agent-1',
    name: 'blogWriterAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    description: 'Generates blog posts, articles, and marketing content with SEO optimization',
    instruction: 'You are a content writer agent. Create engaging blog posts, articles, and marketing content. Optimize for SEO and brand voice consistency.',
    agentVersion: '3',
    createdAt: '2025-02-01T10:00:00.000Z',
    updatedAt: '2025-07-25T11:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-seo-analysis',
        name: 'SEOAnalysis',
        description: 'Analyzes content for SEO optimization',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:seo-analysis`,
        state: 'ENABLED',
        updatedAt: '2025-02-01T10:30:00.000Z',
      },
      {
        id: 'ag-publish-content',
        name: 'PublishContent',
        description: 'Publishes content to the CMS',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:publish-content`,
        state: 'ENABLED',
        updatedAt: '2025-02-01T10:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-brand-guidelines',
        name: 'Brand Guidelines',
        description: 'Brand voice, style guide, and content templates',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-02-01T11:00:00.000Z',
      },
    ],
    guardrail: {
      guardrailId: 'gr-content-brand-1',
      guardrailVersion: '1',
      name: 'Brand Content Guardrail',
    },
    metrics: {
      invocationCount24h: 89,
      avgLatencyMs: 4500,
      errorRate: 0.01,
      totalTokensUsed24h: 380000,
      estimatedCost24h: 1.90,
    },
  },
  {
    id: 'mock-content-agent-2',
    name: 'emailDraftAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.nova-lite-v1:0',
    description: 'Drafts professional emails, newsletters, and communication templates',
    instruction: 'You are an email drafting agent. Create professional emails, newsletters, and templates. Match the appropriate tone for each audience.',
    agentVersion: '1',
    createdAt: '2025-05-20T14:00:00.000Z',
    updatedAt: '2025-05-20T14:00:00.000Z',
    actionGroups: [],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-email-templates',
        name: 'Email Templates',
        description: 'Collection of email templates and communication guidelines',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-05-20T15:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 567,
      avgLatencyMs: 380,
      errorRate: 0.002,
      totalTokensUsed24h: 42000,
      estimatedCost24h: 0.01,
    },
  },
  {
    id: 'mock-content-agent-3',
    name: 'documentSummarizer',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'eu-central-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-haiku-20240307-v1:0',
    description: 'Summarizes long documents, research papers, and reports into concise briefs',
    instruction: 'You are a document summarization agent. Create concise, accurate summaries of long documents while preserving key insights.',
    agentVersion: '2',
    createdAt: '2025-03-25T10:00:00.000Z',
    updatedAt: '2025-06-30T08:15:00.000Z',
    actionGroups: [
      {
        id: 'ag-extract-text',
        name: 'ExtractText',
        description: 'Extracts text from various document formats (PDF, DOCX, etc.)',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:eu-central-1:${MOCK_ACCOUNT_ID}:function:extract-text`,
        state: 'ENABLED',
        updatedAt: '2025-03-25T10:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 234,
      avgLatencyMs: 550,
      errorRate: 0.008,
      totalTokensUsed24h: 180000,
      estimatedCost24h: 0.07,
    },
  },

  // === Search / Retrieval Agents ===
  {
    id: 'mock-search-agent-1',
    name: 'knowledgeSearchAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-haiku-20241022-v1:0',
    description: 'Searches across enterprise knowledge bases to answer employee questions',
    instruction: 'You are a knowledge search agent. Search across internal documentation, wikis, and knowledge bases to provide accurate answers to employee questions.',
    agentVersion: '5',
    createdAt: '2025-01-05T08:00:00.000Z',
    updatedAt: '2025-08-10T10:00:00.000Z',
    actionGroups: [],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-company-wiki',
        name: 'Company Wiki',
        description: 'Internal company wiki and documentation',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-01-05T09:00:00.000Z',
      },
      {
        knowledgeBaseId: 'kb-hr-policies',
        name: 'HR Policies',
        description: 'Human resources policies and employee handbook',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-01-05T09:00:00.000Z',
      },
      {
        knowledgeBaseId: 'kb-eng-docs',
        name: 'Engineering Documentation',
        description: 'Engineering runbooks, architecture docs, and API references',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-01-05T09:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 4521,
      avgLatencyMs: 720,
      errorRate: 0.005,
      totalTokensUsed24h: 890000,
      estimatedCost24h: 1.07,
    },
  },
  {
    id: 'mock-search-agent-2',
    name: 'legalDocSearchAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-sonnet-20240229-v1:0',
    description: 'Searches and retrieves relevant legal documents, contracts, and compliance information',
    instruction: 'You are a legal document search agent. Search legal documents, contracts, and compliance databases to find relevant information.',
    agentVersion: '3',
    createdAt: '2025-02-20T09:00:00.000Z',
    updatedAt: '2025-07-10T14:30:00.000Z',
    actionGroups: [
      {
        id: 'ag-search-contracts',
        name: 'SearchContracts',
        description: 'Searches the contracts management system',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:search-contracts`,
        state: 'ENABLED',
        updatedAt: '2025-02-20T09:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-legal-library',
        name: 'Legal Library',
        description: 'Legal precedents, regulations, and compliance guidelines',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-02-20T10:00:00.000Z',
      },
    ],
    guardrail: {
      guardrailId: 'gr-legal-pii-1',
      guardrailVersion: '2',
      name: 'Legal PII Protection',
    },
    metrics: {
      invocationCount24h: 134,
      avgLatencyMs: 1400,
      errorRate: 0.01,
      totalTokensUsed24h: 210000,
      estimatedCost24h: 1.05,
    },
  },
  {
    id: 'mock-search-agent-3',
    name: 'productSearchAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'ap-northeast-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.nova-micro-v1:0',
    description: 'Fast product search and recommendation agent for the APAC marketplace',
    instruction: 'You are a product search agent. Help users find products, compare options, and get recommendations based on their needs.',
    agentVersion: '1',
    createdAt: '2025-06-15T06:00:00.000Z',
    updatedAt: '2025-06-15T06:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-product-search',
        name: 'ProductSearch',
        description: 'Searches the product catalog',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:ap-northeast-1:${MOCK_ACCOUNT_ID}:function:product-search`,
        state: 'ENABLED',
        updatedAt: '2025-06-15T06:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-apac-products',
        name: 'APAC Product Catalog',
        description: 'Product catalog for the Asia-Pacific market',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-06-15T07:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 3678,
      avgLatencyMs: 210,
      errorRate: 0.003,
      totalTokensUsed24h: 150000,
      estimatedCost24h: 0.03,
    },
  },

  // === Workflow Automation Agents ===
  {
    id: 'mock-workflow-agent-1',
    name: 'cicdPipelineAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.nova-lite-v1:0',
    description: 'Manages CI/CD pipeline operations, deployments, and rollbacks',
    instruction: 'You are a CI/CD pipeline agent. Help with deployment management, pipeline monitoring, and automated rollbacks.',
    agentVersion: '2',
    createdAt: '2025-03-15T12:00:00.000Z',
    updatedAt: '2025-07-05T16:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-trigger-deploy',
        name: 'TriggerDeployment',
        description: 'Triggers a deployment pipeline',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:trigger-deploy`,
        state: 'ENABLED',
        updatedAt: '2025-03-15T12:30:00.000Z',
      },
      {
        id: 'ag-rollback',
        name: 'RollbackDeployment',
        description: 'Rolls back a deployment to a previous version',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:rollback`,
        state: 'ENABLED',
        updatedAt: '2025-03-15T12:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 78,
      avgLatencyMs: 600,
      errorRate: 0.01,
      totalTokensUsed24h: 25000,
      estimatedCost24h: 0.01,
    },
  },
  {
    id: 'mock-workflow-agent-2',
    name: 'incidentResponseAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    description: 'Coordinates incident response, runs diagnostics, and manages escalation workflows',
    instruction: 'You are an incident response agent. Coordinate incident response by running diagnostics, notifying stakeholders, and managing resolution workflows.',
    agentVersion: '3',
    createdAt: '2025-01-25T08:00:00.000Z',
    updatedAt: '2025-08-12T09:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-run-health-check',
        name: 'RunHealthCheck',
        description: 'Runs health checks on affected services',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:health-check`,
        state: 'ENABLED',
        updatedAt: '2025-01-25T08:30:00.000Z',
      },
      {
        id: 'ag-page-oncall',
        name: 'PageOnCall',
        description: 'Pages the on-call engineer via PagerDuty',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:page-oncall`,
        state: 'ENABLED',
        updatedAt: '2025-01-25T08:30:00.000Z',
      },
      {
        id: 'ag-update-status',
        name: 'UpdateStatusPage',
        description: 'Updates the public status page',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:update-status`,
        state: 'ENABLED',
        updatedAt: '2025-01-25T08:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-runbooks',
        name: 'Incident Runbooks',
        description: 'Incident response runbooks and playbooks',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-01-25T09:00:00.000Z',
      },
    ],
    guardrail: {
      guardrailId: 'gr-incident-safety-1',
      guardrailVersion: '1',
      name: 'Incident Response Safety',
    },
    metrics: {
      invocationCount24h: 23,
      avgLatencyMs: 1800,
      errorRate: 0.0,
      totalTokensUsed24h: 45000,
      estimatedCost24h: 0.23,
    },
  },
  {
    id: 'mock-workflow-agent-3',
    name: 'dataIngestionAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-west-2',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.titan-text-express-v1',
    description: 'Orchestrates data ingestion pipelines and monitors data quality',
    instruction: 'You are a data ingestion agent. Manage ETL pipelines, monitor data quality, and handle data ingestion from various sources.',
    agentVersion: '1',
    createdAt: '2025-05-05T13:00:00.000Z',
    updatedAt: '2025-05-05T13:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-start-pipeline',
        name: 'StartPipeline',
        description: 'Starts a data ingestion pipeline',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-west-2:${MOCK_ACCOUNT_ID}:function:start-pipeline`,
        state: 'ENABLED',
        updatedAt: '2025-05-05T13:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 156,
      avgLatencyMs: 450,
      errorRate: 0.008,
      totalTokensUsed24h: 35000,
      estimatedCost24h: 0.01,
    },
  },

  // === Additional Agents (more variety) ===
  {
    id: 'mock-hr-agent-1',
    name: 'hrPolicyAssistant',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.nova-pro-v1:0',
    description: 'Answers HR policy questions and helps employees with benefits enrollment',
    instruction: 'You are an HR policy assistant. Help employees find information about company policies, benefits, PTO, and enrollment processes.',
    agentVersion: '2',
    createdAt: '2025-04-01T09:00:00.000Z',
    updatedAt: '2025-07-15T10:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-benefits-lookup',
        name: 'BenefitsLookup',
        description: 'Looks up employee benefits information',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:benefits-lookup`,
        state: 'ENABLED',
        updatedAt: '2025-04-01T09:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-hr-handbook',
        name: 'Employee Handbook',
        description: 'Complete employee handbook and company policies',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-04-01T10:00:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 312,
      avgLatencyMs: 890,
      errorRate: 0.006,
      totalTokensUsed24h: 78000,
      estimatedCost24h: 0.31,
    },
  },
  {
    id: 'mock-translation-agent-1',
    name: 'translationAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-haiku-20240307-v1:0',
    description: 'Translates content between languages while preserving context and tone',
    instruction: 'You are a translation agent. Translate content accurately between languages while preserving the original tone, context, and cultural nuances.',
    agentVersion: '1',
    createdAt: '2025-05-10T12:00:00.000Z',
    updatedAt: '2025-05-10T12:00:00.000Z',
    actionGroups: [],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-glossary',
        name: 'Company Glossary',
        description: 'Company-specific terminology and preferred translations',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-05-10T12:30:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 678,
      avgLatencyMs: 340,
      errorRate: 0.004,
      totalTokensUsed24h: 156000,
      estimatedCost24h: 0.06,
    },
  },
  {
    id: 'mock-compliance-agent-1',
    name: 'complianceCheckAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-sonnet-20240229-v1:0',
    description: 'Verifies compliance with SOC2, HIPAA, and GDPR regulations',
    instruction: 'You are a compliance checking agent. Analyze configurations and processes against SOC2, HIPAA, and GDPR requirements to identify compliance gaps.',
    agentVersion: '3',
    createdAt: '2025-02-28T08:00:00.000Z',
    updatedAt: '2025-08-15T09:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-scan-config',
        name: 'ScanConfiguration',
        description: 'Scans infrastructure configuration for compliance violations',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:scan-config`,
        state: 'ENABLED',
        updatedAt: '2025-02-28T08:30:00.000Z',
      },
      {
        id: 'ag-generate-report-compliance',
        name: 'GenerateComplianceReport',
        description: 'Generates compliance audit reports',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:compliance-report`,
        state: 'ENABLED',
        updatedAt: '2025-02-28T08:30:00.000Z',
      },
    ],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-compliance-standards',
        name: 'Compliance Standards',
        description: 'SOC2, HIPAA, and GDPR regulatory requirements',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-02-28T09:00:00.000Z',
      },
    ],
    guardrail: {
      guardrailId: 'gr-compliance-strict-1',
      guardrailVersion: '1',
      name: 'Strict Compliance Guardrail',
    },
    metrics: {
      invocationCount24h: 45,
      avgLatencyMs: 2400,
      errorRate: 0.005,
      totalTokensUsed24h: 120000,
      estimatedCost24h: 0.60,
    },
  },
  {
    id: 'mock-meeting-agent-1',
    name: 'meetingSummaryAgent',
    type: 'bedrock-agent',
    status: 'PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.nova-lite-v1:0',
    description: 'Summarizes meeting recordings and generates action items',
    instruction: 'You are a meeting summary agent. Process meeting transcripts, generate concise summaries, extract action items, and identify key decisions.',
    agentVersion: '2',
    createdAt: '2025-06-20T10:00:00.000Z',
    updatedAt: '2025-07-30T14:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-process-transcript',
        name: 'ProcessTranscript',
        description: 'Processes meeting transcripts from recording services',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-east-1:${MOCK_ACCOUNT_ID}:function:process-transcript`,
        state: 'ENABLED',
        updatedAt: '2025-06-20T10:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 189,
      avgLatencyMs: 520,
      errorRate: 0.007,
      totalTokensUsed24h: 98000,
      estimatedCost24h: 0.03,
    },
  },

  // === FAILED Status Agents ===
  {
    id: 'mock-failed-agent-1',
    name: 'deprecatedChatbot',
    type: 'bedrock-agent',
    status: 'FAILED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'amazon.titan-text-lite-v1',
    description: 'Legacy chatbot that failed during last update due to invalid model configuration',
    instruction: 'You are a general-purpose chatbot.',
    agentVersion: '1',
    createdAt: '2024-11-01T10:00:00.000Z',
    updatedAt: '2025-03-15T09:00:00.000Z',
    actionGroups: [],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 0,
      avgLatencyMs: 0,
      errorRate: 1.0,
      totalTokensUsed24h: 0,
      estimatedCost24h: 0,
    },
  },
  {
    id: 'mock-failed-agent-2',
    name: 'brokenIntegrationAgent',
    type: 'bedrock-agent',
    status: 'FAILED',
    region: 'eu-west-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'meta.llama3-70b-instruct-v1:0',
    description: 'Integration agent that failed due to missing Lambda function permissions',
    instruction: 'You are an integration agent that connects various third-party services.',
    agentVersion: '2',
    createdAt: '2025-02-10T11:00:00.000Z',
    updatedAt: '2025-06-01T14:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-sync-salesforce',
        name: 'SyncSalesforce',
        description: 'Syncs data with Salesforce (currently broken)',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:eu-west-1:${MOCK_ACCOUNT_ID}:function:sync-salesforce`,
        state: 'DISABLED',
        updatedAt: '2025-02-10T11:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 0,
      avgLatencyMs: 0,
      errorRate: 1.0,
      totalTokensUsed24h: 0,
      estimatedCost24h: 0,
    },
  },

  // === NOT_PREPARED Status Agents ===
  {
    id: 'mock-notprepared-agent-1',
    name: 'experimentalRAGAgent',
    type: 'bedrock-agent',
    status: 'NOT_PREPARED',
    region: 'us-east-1',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'meta.llama3-8b-instruct-v1:0',
    description: 'Experimental RAG agent still being configured and tested',
    instruction: 'You are an experimental RAG agent for testing new retrieval augmented generation patterns.',
    agentVersion: 'DRAFT',
    createdAt: '2025-08-01T10:00:00.000Z',
    updatedAt: '2025-08-01T10:00:00.000Z',
    actionGroups: [],
    knowledgeBases: [
      {
        knowledgeBaseId: 'kb-test-data',
        name: 'Test Data',
        description: 'Test knowledge base for experimentation',
        dataSourceType: 'S3',
        embeddingModel: 'amazon.titan-embed-text-v2:0',
        status: 'ACTIVE',
        updatedAt: '2025-08-01T10:30:00.000Z',
      },
    ],
    metrics: {
      invocationCount24h: 5,
      avgLatencyMs: 3500,
      errorRate: 0.4,
      totalTokensUsed24h: 2000,
      estimatedCost24h: 0.001,
    },
  },
  {
    id: 'mock-notprepared-agent-2',
    name: 'multimodalAgent',
    type: 'bedrock-agent',
    status: 'NOT_PREPARED',
    region: 'us-west-2',
    accountId: MOCK_ACCOUNT_ID,
    foundationModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    description: 'Multimodal agent being developed to process images and text together',
    instruction: 'You are a multimodal agent. Process both images and text to provide comprehensive analysis.',
    agentVersion: 'DRAFT',
    createdAt: '2025-08-10T15:00:00.000Z',
    updatedAt: '2025-08-10T15:00:00.000Z',
    actionGroups: [
      {
        id: 'ag-process-image',
        name: 'ProcessImage',
        description: 'Processes and analyzes uploaded images',
        executionType: 'LAMBDA',
        lambdaArn: `arn:aws:lambda:us-west-2:${MOCK_ACCOUNT_ID}:function:process-image`,
        state: 'ENABLED',
        updatedAt: '2025-08-10T15:30:00.000Z',
      },
    ],
    knowledgeBases: [],
    metrics: {
      invocationCount24h: 0,
      avgLatencyMs: 0,
      errorRate: 0,
      totalTokensUsed24h: 0,
      estimatedCost24h: 0,
    },
  },
];

export function getMockAgents(region?: string, accountId?: string): AgentInventoryItem[] {
  let agents = allMockAgents;

  if (region) {
    agents = agents.filter((a) => a.region === region);
  }

  if (accountId) {
    agents = agents.filter((a) => a.accountId === accountId);
  }

  return agents;
}
